---
- hosts: server1
  become: yes
  tasks:
          - name: add firewall tule for http and https
            firewalld:
                    zone: public
                    service: "{{ item }}"
                    permanent: yes
                    immediate: yes
                    state: disabled
            loop:
                    - https
                    - http
          - name: add firewall rule for 80
            firewalld:
                    port: 8080-8084/tcp
                    permanent: yes
                    immediate: yes
                    state: disabled
          - name: forward port 443 to 8443
            firewalld:
                    rich_rule: rule family=ipv4 forward-port port=443 protocol=tcp to-port=8443
                    permanent: yes
                    immediate: yes
                    state: disabled
